# Generated by Django 4.2.23 on 2025-08-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientdoctorassignment_medicalrecord_encryptionkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='encrypted_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
