# Generated by Django 4.2.23 on 2025-08-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_medicalrecord_encrypted_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='encrypted_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
