# Generated by Django 4.2.23 on 2025-08-14 15:05

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_medicalrecord_encrypted_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.FileField(upload_to='records/')),
            ],
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='encrypted_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
