# Generated by Django 4.2.23 on 2025-08-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_medicalrecord_encrypted_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='encrypted_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
